"""refactor goal to weekly goals

Revision ID: 0cf6c92f05c3
Revises: bc1f4b154e03
Create Date: 2026-06-23 16:00:03.202053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf6c92f05c3'
down_revision: Union[str, Sequence[str], None] = 'bc1f4b154e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('goals', sa.Column('week_number', sa.Integer(), nullable=False))
    op.alter_column('goals', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('goals', 'target_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.create_unique_constraint('uq_goal_user_week', 'goals', ['user_id', 'year', 'week_number'])
    op.drop_column('goals', 'description')
    op.drop_column('goals', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('goals', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint('uq_goal_user_week', 'goals', type_='unique')
    op.alter_column('goals', 'target_hours',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('goals', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('goals', 'week_number')
    op.drop_column('goals', 'year')
    # ### end Alembic commands ###
