"""goal v3 support weekly question goals

Revision ID: 5b937552d854
Revises: 7d99243b2081
Create Date: 2026-06-28 16:15:36.453664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b937552d854'
down_revision: Union[str, Sequence[str], None] = '7d99243b2081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('target_questions', sa.Integer(), nullable=True))
    op.alter_column('goals', 'target_hours',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'target_hours',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('goals', 'target_questions')
    # ### end Alembic commands ###
