"""session v2 model

Revision ID: 7d99243b2081
Revises: 0cf6c92f05c3
Create Date: 2026-06-24 10:52:27.221084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d99243b2081'
down_revision: Union[str, Sequence[str], None] = '0cf6c92f05c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('sessions', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('sessions', sa.Column('session_type', sa.String(length=20), nullable=True))
    op.add_column('sessions', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('paused_seconds', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('questions_total', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('questions_correct', sa.Integer(), nullable=True))

    # backfill seguro
    op.execute("UPDATE sessions SET status = 'finished' WHERE status IS NULL")
    op.execute("UPDATE sessions SET paused_seconds = 0 WHERE paused_seconds IS NULL")

    # agora trava constraints
    op.alter_column('sessions', 'status', nullable=False)
    op.alter_column('sessions', 'paused_seconds', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'questions_correct')
    op.drop_column('sessions', 'questions_total')
    op.drop_column('sessions', 'paused_at')
    op.drop_column('sessions', 'paused_seconds')
    op.drop_column('sessions', 'description')
    op.drop_column('sessions', 'session_type')
    op.drop_column('sessions', 'status')
    # ### end Alembic commands ###
